### ISSUE TITLE
Copy & paste

### ISSUE THREAD

**Issue by ehj000** [4ment/seqotron#1]
Hi,
The tool looks very interesting, and I have installed the tool on a Mac OS Sierra (10.12.3). UInfortunately, I am not able to copy part of a selected sequence (or alignment) and paste it into another tool, eg. a text editor.
Best, Erik

**Comment by 4ment** [comment]
Hi Erik,
Seqotron can only copy/paste sequences when they are selected by name (in the left panel). You have to delete parts of the alignment first and then select the sequence of interest.
Cheers

**Comment by ehj000** [comment]
Hi Mathieu,
Thank you for your answer. I still think it is a bit complicated and not a fast enough solution. Maybe this is something that can be come in a later version?

Also, it would be great if one could open a new sequence directly from the clipboard

Cheers
Erik

On 07 Feb 2017, at 23:14, Mathieu Fourment <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Erik,
Seqotron can only copy/paste sequences when they are selected by name (in the left panel). You have to delete parts of the alignment first and then select the sequence of interest.
Cheers
