### ISSUE TITLE
Can you create a linux or windows distribution

### ISSUE THREAD

**Issue by sanyalab** [4ment/seqotron#6]
Hello Mathieu

A request. I would like to try this tool. Unfortunately I work on linux. Can you create a linux or a windows executable? I am guessing that compiling from source on a linux machine will not do me any good either. Please let me know.

Thanks
Abhijit

**Comment by 4ment** [comment]
Hi, seqotron uses the Cocoa library which is Apple's native API so
compiling it on Linux is not possible. I recommend you have a look at
AliView, it is written in Java and therefore cross platform.

**Comment by starsareintherose** [comment]
Maybe you can try GNUstep to build it, but maybe you need some patch
